version: '3.7'

x-db-environment:
  &db-environment
    WORDPRESS_DB_HOST: wonolog-db
    WORDPRESS_DB_NAME: wordpress
    WORDPRESS_DB_USER: wordpress
    WORDPRESS_DB_PASSWORD: wordpress

x-wp-volume:
  &wp-volume
    -   type: bind
        source: ../../../
        target: /var/www/html

services:
    db:
        image: mariadb:10.5
        container_name: wonolog-db
        environment:
            MARIADB_ROOT_PASSWORD: wordpress
            MARIADB_DATABASE: wordpress
            MARIADB_USER: wordpress
            MARIADB_PASSWORD: wordpress

    php81:
        container_name: wonolog-php-81
        build:
            context: .
            dockerfile: ./php81/Dockerfile
        depends_on:
            - db
        environment:
          *db-environment
        volumes:
          *wp-volume
    php82:
        container_name: wonolog-php-82
        build:
            context: .
            dockerfile: ./php82/Dockerfile
        depends_on:
            - db
        environment:
          *db-environment
        volumes:
          *wp-volume
    php83:
        container_name: wonolog-php-83
        build:
            context: .
            dockerfile: ./php83/Dockerfile
        depends_on:
            - db
        environment:
          *db-environment
        volumes:
          *wp-volume
    php84:
        container_name: wonolog-php-84
        build:
            context: .
            dockerfile: ./php84/Dockerfile
        depends_on:
            - db
        environment:
          *db-environment
        volumes:
          *wp-volume
    php85:
      container_name: wonolog-php-85
      build:
        context: .
        dockerfile: ./php85/Dockerfile
      depends_on:
        - db
      environment:
        *db-environment
      volumes:
        *wp-volume