version: '3.7'

x-db-environment:
  &db-environment
    WORDPRESS_DB_HOST: wonolog-db
    WORDPRESS_DB_NAME: wordpress
    WORDPRESS_DB_USER: wordpress
    WORDPRESS_DB_PASSWORD: wordpress

x-wp-volume:
  &wp-volume
    -   type: bind
        source: ../../../
        target: /var/www/html

services:
    db:
        image: mariadb:10.5
        container_name: wonolog-db
        environment:
            MARIADB_ROOT_PASSWORD: wordpress
            MARIADB_DATABASE: wordpress
            MARIADB_USER: wordpress
            MARIADB_PASSWORD: wordpress

    php81:
        container_name: wonolog-php-81
        build:
            context: ./php81
        depends_on:
            - db
        environment:
          *db-environment
        volumes:
          *wp-volume
    php82:
        container_name: wonolog-php-82
        build:
            context: ./php82
        depends_on:
            - db
        environment:
          *db-environment
        volumes:
          *wp-volume
