name: Integration tests
on:
    workflow_dispatch:
    push:
        branches: [ 'master', '2.x' ]
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    integration-tests:
        runs-on: ubuntu-latest
        if: ${{ !contains(github.event.head_commit.message, 'skip integration') }}
        env:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
        services:
            mysql:
                image: mysql:5.7
                ports:
                    - 3306:3306
                env:
                    MYSQL_DATABASE: ${{ env.WORDPRESS_DB_NAME }}
                    MYSQL_USER: ${{ env.WORDPRESS_DB_USER }}
                    MYSQL_PASSWORD: ${{ env.WORDPRESS_DB_PASSWORD }}
        steps:
            -   name: Chekout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-ver: 7.4
                    coverage: none
                    tools: wp-cli

            -   name: Install dependencies
                uses: ramsey/composer-install@v1

            -   name: Run integration tests
                run: ./vendor/bin/phpunit --testsuite=integration --no-coverage
