name: Integration tests
on:
    workflow_dispatch:
    push:
        branches: [ 'master', '2.x' ]
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
jobs:
    integration-tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                php-service: [ 'php74' ]
        steps:
            -   uses: actions/checkout@v2

            -   name: Run integration tests
                working-directory: ./.github/workflows/docker
                run: docker-compose run -T --rm ${{ matrix.php-service }} sh -c "composer update && composer tests:integration"
