name: Integration tests
on:
    workflow_dispatch:
    push:
        branches: [ 'master', '2.x' ]
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
env:
    DB_HOST: mysql
    DB_USER: wordpress
    DB_PASSWORD: wordpress
    DB_NAME: wordpress
jobs:
    integration-tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                php-ver: [ '7.4' ]
        container:
            image: ${{ format('wordpress:cli-2.5-php{0}', matrix.php-ver) }}
            volumes:
                - ${{ github.workspace }}:/var/www/html
            options: '--user root'
            env:
                WORDPRESS_DB_HOST: ${{ env.DB_HOST }}
                WORDPRESS_DB_USER: ${{ env.DB_USER }}
                WORDPRESS_DB_PASSWORD: ${{ env.DB_PASSWORD }}
                WORDPRESS_DB_NAME: ${{ env.DB_NAME }}
        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_DATABASE: ${{ env.DB_NAME }}
                    MYSQL_USER: ${{ env.DB_USER }}
                    MYSQL_PASSWORD: ${{ env.DB_PASSWORD }}
        steps:
            -   name: Install Git in the container
                run: |
                    apk update
                    apk add git

            -   name: Checkout
                uses: actions/checkout@v2

            -   run: ls -a
