name: Integration tests
on:
    workflow_dispatch:
    push:
        branches: [ 'master', '2.x' ]
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
jobs:
    integration-tests:
        runs-on: ubuntu-latest
        if: ${{ !contains(github.event.head_commit.message, 'skip integration') }}
        strategy:
            fail-fast: true
            matrix:
                php-service: [ 'php73', 'php74', 'php80' ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Copy wait-for
                run: cp .github/workflows/docker/wait-for.sh .github/workflows/docker/${{ matrix.php-service }}/wait-for.sh

            -   name: Run integration tests
                working-directory: .github/workflows/docker
                run: docker-compose run --rm ${{ matrix.php-service }} sh -c "wait-for.sh wonolog-mysql:3306 -t 15 -- composer update && composer tests:integration"
