name: Integration tests
on:
    workflow_dispatch:
    push:
        branches: [ 'master', '2.x' ]
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    integration-tests:
        runs-on: ubuntu-latest
        container: wordpress:cli-2.5-php7.4
        env:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_DATABASE: ${{ env.WORDPRESS_DB_NAME }}
                    MYSQL_USER: ${{ env.WORDPRESS_DB_USER }}
                    MYSQL_PASSWORD: ${{ env.WORDPRESS_DB_PASSWORD }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Install dependencies
                uses: ramsey/composer-install@v1

            -   name: Run integration tests
                run: ./vendor/bin/phpunit --testsuite=integration --no-coverage
