name: PHP Integration Tests

on:
    push:
        paths:
            - '**workflows/php-integration-tests.yml'
            - '**workflows/docker/**'
            - '**.php'
            - '**phpunit.xml.dist'
            - '**composer.json'
    pull_request:
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    integration-tests:
        runs-on: ubuntu-latest
        if: ${{ !contains(github.event.head_commit.message, 'skip integration') }}
        strategy:
            fail-fast: false
            matrix:
                php-service: [ '81', '82' ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Copy wait-for
                run: |
                    cp .github/workflows/docker/install-composer.sh .github/workflows/docker/php${{ matrix.php-service }}/install-composer.sh
                    cp .github/workflows/docker/wait-for.sh .github/workflows/docker/php${{ matrix.php-service }}/wait-for.sh

            -   name: Run integration tests
                working-directory: .github/workflows/docker
                run: docker-compose run --rm php${{ matrix.php-service }} sh -c "wait-for.sh wonolog-mysql:3306 -t 15 -- composer update && composer tests:integration"
