name: PHP Static Code Analysis

on:
    push:
        paths:
            - '**workflows/php-static-analysis.yml'
            - '**.php'
            - '**phpcs.xml.dist'
            - '**phpstan.neon.dist'
            - '**composer.json'
    pull_request:
    workflow_dispatch:
        inputs:
            jobs:
                required: true
                type: choice
                default: 'Run all'
                description: 'Choose jobs to run'
                options:
                    - 'Run all'
                    - 'Run PHPCS only'
                    - 'Run static analysis only'
                    - 'Run lint only'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint-php:
        uses: inpsyde/reusable-workflows/.github/workflows/lint-php.yml@main
        if: ${{ (github.event_name != 'workflow_dispatch') || ((github.event.inputs.jobs == 'Run all') || (github.event.inputs.jobs == 'Run lint only')) }}
        strategy:
            matrix:
                php-version: ["8.1", "8.2", "8.3", "8.4"]
                dependency-versions: ['highest', 'lowest']
        with:
            PHP_VERSION: ${{ matrix.php-version }}

    coding-standards-analysis-php:
        if: ${{ (github.event_name != 'workflow_dispatch') || ((github.event.inputs.jobs == 'Run all') || (github.event.inputs.jobs == 'Run PHPCS only')) }}
        uses: inpsyde/reusable-workflows/.github/workflows/coding-standards-php.yml@main
        with:
            PHP_VERSION: '8.1'

    static-code-analysis-php:
        if: ${{ (github.event_name != 'workflow_dispatch') || ((github.event.inputs.jobs == 'Run all') || (github.event.inputs.jobs == 'Run static analysis only')) }}
        uses: inpsyde/reusable-workflows/.github/workflows/static-analysis-php.yml@main
        strategy:
            matrix:
                php-version: ["8.1", "8.2", "8.3", "8.4"]
                dependency-versions: ['highest', 'lowest']
        with:
            PHP_VERSION: ${{ matrix.php-version }}
            PHPSTAN_ARGS: "--no-progress --memory-limit=1G ${{ matrix.dependency-versions == 'highest' && '--configuration=phpstan.monolog3.neon' || '--configuration=phpstan.monolog2.neon' }}"
