name: PHP Static Code Analysis

on:
    push:
        paths:
            - '**workflows/php-static-analysis.yml'
            - '**.php'
            - '**phpcs.xml.dist'
            - '**psalm.xml'
            - '**composer.json'
    pull_request:
    workflow_dispatch:
        inputs:
            jobs:
                required: true
                type: choice
                default: 'Run all'
                description: 'Choose jobs to run'
                options:
                    - 'Run all'
                    - 'Run PHPCS only'
                    - 'Run Psalm only'
                    - 'Run lint only'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint-php:
        uses: inpsyde/reusable-workflows/.github/workflows/lint-php.yml@main
        if: ${{ (github.event_name != 'workflow_dispatch') || ((github.event.inputs.jobs == 'Run all') || (github.event.inputs.jobs == 'Run lint only')) }}
        with:
            PHP_MATRIX: '["7.2", "7.3", "7.4", "8.0", "8.1", "8.2"]'

    coding-standards-analysis-php:
        if: ${{ (github.event_name != 'workflow_dispatch') || ((github.event.inputs.jobs == 'Run all') || (github.event.inputs.jobs == 'Run PHPCS only')) }}
        uses: inpsyde/reusable-workflows/.github/workflows/coding-standards-php.yml@main

    static-code-analysis-php:
        if: ${{ (github.event_name != 'workflow_dispatch') || ((github.event.inputs.jobs == 'Run all') || (github.event.inputs.jobs == 'Run Psalm only')) }}
        uses: inpsyde/reusable-workflows/.github/workflows/static-analysis-php.yml@main
