name: PHP Unit Tests

on:
    push:
        paths:
            - '**workflows/php-unit-tests.yml'
            - '**.php'
            - '**phpunit.xml.dist'
            - '**composer.json'
    pull_request:
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    unit-tests:
        runs-on: ubuntu-latest
        if: ${{ !contains(github.event.head_commit.message, 'skip unit') }}

        strategy:
            fail-fast: false
            matrix:
                php-versions: [ '8.2', '8.3', '8.4', '8.5' ]
                dependency-versions: ['highest', 'lowest']

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  ini-values: zend.assertions=1, error_reporting=${{ ((matrix.php-versions == '8.4' || matrix.php-versions == '8.5') && 'E_ALL') || 'E_ALL & ~E_DEPRECATED' }}, display_errors=On
                  coverage: none

            - name: Install Composer dependencies
              uses: ramsey/composer-install@v3
              with:
                dependency-versions: ${{ matrix.dependency-versions }}

            - name: Run unit tests
              run: composer tests:unit:no-cov

