name: PHP Quality Assurance

on:
    push:
        paths:
            - '**workflows/php-qa.yml'
            - '**.php'
            - '**phpunit.xml.dist'
            - '**composer.json'
    pull_request:
        paths:
            - '**workflows/php-qa.yml'
            - '**.php'
            - '**phpunit.xml.dist'
            - '**composer.json'
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:

    unit-tests:
        runs-on: ubuntu-latest
        env:
            USE_COVERAGE: no
        strategy:
            fail-fast: false
            matrix:
                php-ver: [ '5.6', '7.0', '7.1' ]
        steps:
            -   name: Update "USE_COVERAGE" env var based on matrix
                if: ${{ matrix.php-ver == '5.6' }}
                run: echo "USE_COVERAGE=yes" >> $GITHUB_ENV

            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-ver }}
                    ini-values: zend.assertions=1, error_reporting=E_ALL, display_errors=On }}
                    coverage: ${{ ((env.USE_COVERAGE == 'yes') && 'xdebug') || 'none' }}

            -   name: Install dependencies
                uses: ramsey/composer-install@v2

            -   name: Run unit tests
                run: ./vendor/bin/phpunit ${{ ((env.USE_COVERAGE == 'yes') && '--coverage-html=coverage-report') || '--no-coverage' }}

            -   name: Upload coverage report
                uses: actions/upload-artifact@v3
                if: ${{ env.USE_COVERAGE == 'yes' }}
                with:
                    name: coverage-report
                    path: coverage-report/

    lint:
        runs-on: ubuntu-latest
        if: ${{ !contains(github.event.head_commit.message, 'skip lint') }}
        strategy:
            fail-fast: true
            matrix:
                php-ver: [ '5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1' ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-ver }}
                    ini-values: zend.assertions=1, error_reporting=E_ALL, display_errors=On
                    tools: parallel-lint

            -   name: Check syntax error in sources
                run: parallel-lint ./src/ ./inc/
